grocery_app/routes.py
from flask import Blueprint, request, render_template, redirect, url_for, flash
from flask_login import login_user, logout_user, login_required, current_user
from datetime import date, datetime
from grocery_app.models import GroceryStore, GroceryItem, User
from grocery_app.forms import GroceryStoreForm, GroceryItemForm, SignUpForm, LoginForm
from grocery_app import bcrypt

# Import app and db from grocery_app package so that we can run app
from grocery_app import app, db

main = Blueprint("main", __name__)

##########################################
#           Routes                       #
##########################################

@main.route('/')
def homepage():
    """Display all grocery stores."""
    all_stores = GroceryStore.query.all()
    print(all_stores)
    return render_template('home.html', all_stores=all_stores)

@main.route('/new_store', methods=['GET', 'POST'])
@login_required
def new_store():
    """Add a new grocery store."""
    # Create a GroceryStoreForm
    form = GroceryStoreForm()

    # If form was submitted and was valid:
    # - create a new GroceryStore object and save it to the database,
    # - flash a success message, and
    # - redirect the user to the store detail page.
    if form.validate_on_submit(): 
        new_store = GroceryStore(
            title=form.title.data,
            address=form.address.data,
            created_by=current_user
        )
        db.session.add(new_store)
        db.session.commit()

        flash('New grocery store was created successfully.')
        return redirect(url_for('main.store_detail', store_id=new_store.id))

    # Send the form to the template and use it to render the form fields
    return render_template('new_store.html', form=form)

@main.route('/new_item', methods=['GET', 'POST'])
@login_required
def new_item():
    """Add a new grocery store."""
    # Create a GroceryItemForm
    form = GroceryItemForm()

    # If form was submitted and was valid:
    # - create a new GroceryItem object and save it to the database,
    # - flash a success message, and
    # - redirect the user to the item detail page.
    if form.validate_on_submit(): 
        new_item = GroceryItem(
            name=form.name.data,
            price=form.price.data,
            category=form.category.data,
            photo_url=form.photo_url.data,
            store=form.store.data,
            created_by=current_user
        )
        db.session.add(new_item)
        db.session.commit()

        flash('New grocery item was created successfully.')
        return redirect(url_for('main.item_detail', item_id=new_item.id))

    # Send the form to the template and use it to render the form fields
    return render_template('new_item.html', form=form)

@main.route('/store/<store_id>', methods=['GET', 'POST'])
@login_required
def store_detail(store_id):
    """Display grocery store details with update form below."""
    store = GroceryStore.query.get(store_id)
    # TCreate a GroceryStoreForm and pass in `obj=store`
    form = GroceryStoreForm(obj=store)

    # If form was submitted and was valid:
    # - update the GroceryStore object and save it to the database,
    # - flash a success message, and
    # - redirect the user to the store detail page.
    if form.validate_on_submit(): 
        store.title = form.title.data
        store.address = form.address.data
        
        db.session.add(store)
        db.session.commit()

        flash('The grocery store was updated successfully.')
        return redirect(url_for('main.store_detail', store_id=store.id))

    # Send the form to the template and use it to render the form fields
    store = GroceryStore.query.get(store_id)
    return render_template('store_detail.html', store=store, form=form)

@main.route('/item/<item_id>', methods=['GET', 'POST'])
@login_required
def item_detail(item_id):
    """Display grocery item details with update form below."""
    item = GroceryItem.query.get(item_id)
    # Create a GroceryItemForm and pass in `obj=item`
    form = GroceryItemForm(obj=item)

    # If form was submitted and was valid:
    # - update the GroceryItem object and save it to the database,
    # - flash a success message, and
    # - redirect the user to the item detail page.
    if form.validate_on_submit(): 
        item.name = form.name.data
        item.price = form.price.data
        item.category = form.category.data
        item.photo_url = form.photo_url.data
        item.store = form.store.data
        
        db.session.add(item)
        db.session.commit()

        flash('The grocery item was updated successfully.')
        return redirect(url_for('main.item_detail', item_id=item.id))

    # Send the form to the template and use it to render the form fields
    item = GroceryItem.query.get(item_id)
    return render_template('item_detail.html', item=item, form=form)


@main.route('/add_to_shopping_list/<item_id>', methods=['POST'])
def add_to_shopping_list(item_id):
    """Route for button that adds item to current_user's shopping list."""
    # Get item using its id
    item = GroceryItem.query.get(item_id)

    # Inform user if item is already in shopping list
    if item in current_user.shopping_list_items:
        flash('The grocery item is already in your shopping list.')
    # Otherwise, add item to shopping list, update database, and display success message to user
    else:
        current_user.shopping_list_items.append(item)

        db.session.add(current_user)
        db.session.commit()
        flash('The grocery item was added to your shopping list successfully.')

    return redirect(url_for('main.item_detail', item_id=item_id))


@main.route('/remove_from_shopping_list/<item_id>', methods=['POST'])
def remove_from_shopping_list(item_id):
    """Route for button that removes item from current_user's shopping list."""
    # Get item using its id
    item = GroceryItem.query.get(item_id)

    # Inform user if item is already not in shopping list
    if item not in current_user.shopping_list_items:
        flash('The grocery item was not in your shopping list.')
    # Otherwise, add item to shopping list, update database, and display success message to user
    else:
        current_user.shopping_list_items.remove(item)

        db.session.add(current_user)
        db.session.commit()
        flash('The grocery item was removed from your shopping list successfully.')

    return redirect(url_for('main.item_detail', item_id=item_id))


@main.route('/shopping_list')
@login_required
def shopping_list():
    """Route for users to see items in their shopping list."""
    # Get logged in user's shopping list items
    user_shopping_items = current_user.shopping_list_items
    # Display shopping list items in a template
    return render_template('shopping_list.html', user_shopping_items=user_shopping_items)






###########################
# Auth routes
###########################

auth = Blueprint("auth", __name__)

@auth.route('/signup', methods=['GET', 'POST'])
def signup():
    """Sign up a user with a new account."""
    print('in signup')
    form = SignUpForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user = User(
            username=form.username.data,
            password=hashed_password
        )
        db.session.add(user)
        db.session.commit()
        flash('Account Created.')
        print('created')
        return redirect(url_for('auth.login'))
    print(form.errors)
    return render_template('signup.html', form=form)


@auth.route('/login', methods=['GET', 'POST'])
def login():
    """Log in a user with an existing account."""
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(username=form.username.data).first()
        if user and bcrypt.check_password_hash(user.password, form.password.data):
            login_user(user, remember=True)
            next_page = request.args.get('next')
            return redirect(next_page if next_page else url_for('main.homepage'))
    return render_template('login.html', form=form)

@auth.route('/logout')
@login_required
def logout():
    """Log user out of the account."""
    logout_user()
    return redirect(url_for('main.homepage'))

grocery_app/templates/base.html
<!DOCTYPE html>
<html>
    <head>
        <title>Grocery Store Tracker</title>
        <link rel="stylesheet" href="/static/style.css">
        <link rel="preconnect" href="https://fonts.gstatic.com">
        <link href="https://fonts.googleapis.com/css2?family=Open+Sans:wght@400;700&display=swap" rel="stylesheet">
    </head>
    <body>
        <div id="content">
            {% for message in get_flashed_messages() %}
                <p>{{ message }}</p>
            {% endfor %}
            <nav>
                <a href="/">Home</a>
                <div>
                    <!-- Only show these links if the current user is 
                        authenticated (logged in)! -->
                        {% if current_user.is_authenticated %}
                        <a href="/shopping_list">My Shopping List</a>
                        <a href="/logout">Log Out</a>
    
                        <!-- Only show these links if the current user is NOT
                            authenticated (logged out)! -->
                        {% else %}
                        <a href="/signup">Sign Up</a>
                        <a href="/login">Log In</a>
    
                        {% endif %}
                    <a href="/new_store">New Store</a>
                    <a href="/new_item">New Item</a>
                </div>
            </nav>
            {% block content %}{% endblock %}
        </div>
    </body>
</html>

grocery_app/templates/home.html
{% extends 'base.html' %}
{% block content %}

<h1>Grocery Store Tracker</h1>

<p><em>The best place to track prices and find the hottest deals!</em></p>

<h2>All Stores</h2>

{% for store in all_stores %}
<div class="store">
    <a href="/store/{{ store.id }}">{{ store.title }}</a> - 
    {{ store.items|length }} items
    <p><strong>Address:</strong> {{ store.address }}</p>
</div>
{% endfor %}

{% endblock %}

grocery_app/templates/item_detail.html
{% extends 'base.html' %}
{% block content %}

<h1>Item - {{ item.name }}</h1>

<p><img src="{{ item.photo_url }}" width="250px" height="250px"></p>

<p><strong>Price:</strong> {{ item.price }}</p>

<p><strong>Category:</strong> {{ item.category }}</p>

<p><strong>Store:</strong> {{ item.store.title }}</p>

<p><em>Created by:</em> {{ item.created_by }}</p>

<form method="POST" action="/add_to_shopping_list/{{ item.id }}">
    <label>Add this item to My Shopping List</label>
    <input type="submit" value="Add">
</form>

<form method="POST" action="/remove_from_shopping_list/{{ item.id }}">
    <label>Remove this item from My Shopping List</label>
    <input type="submit" value="Remove">
</form>


<h2>Edit Item</h2>

<form method="POST" action="{{ url_for('main.item_detail', item_id=item.id) }}">

    {{ form.csrf_token }}

    <fieldset>
        <legend>Please enter your information:</legend>

            {{ form.name.label }}
            {{ form.name }}
            <ul>
                {% for error in form.name.errors %}
                <li class="error">{{ error }}</li>
                {% endfor %}
            </ul>
            
            {{ form.price.label }}
            {{ form.price}}
            <ul>
                {% for error in form.price.errors %}
                <li class="error">{{ error }}</li>
                {% endfor %}
            </ul>

            {{ form.category.label }}
            {{ form.category }}
            <ul>
                {% for error in form.category.errors %}
                <li class="error">{{ error }}</li>
                {% endfor %}
            </ul>
            
            {{ form.photo_url.label }}
            {{ form.photo_url}}
            <ul>
                {% for error in form.photo_url.errors %}
                <li class="error">{{ error }}</li>
                {% endfor %}
            </ul>

            {{ form.store.label }}
            {{ form.store}}
            <ul>
                {% for error in form.store.errors %}
                <li class="error">{{ error }}</li>
                {% endfor %}
            </ul>
                
            {{ form.submit }}

    </fieldset>
</form>

{% endblock %}

grocery_app/templates/login.html
{% extends 'base.html' %}
{% block content %}

<h1>Log In</h1>

<form action="/login" method="POST">
    {{ form.csrf_token }}
    <fieldset>
        <legend>Enter your credentials</legend>

        {{ form.username.label }}
        {{ form.username }}
        <ul>
        {% for error in form.username.errors %}
            <li class="error">{{ error }}</li>
        {% endfor %}
        </ul>

        {{ form.password.label }}
        {{ form.password }}
        <ul>
        {% for error in form.password.errors %}
            <li class="error">{{ error }}</li>
        {% endfor %}
        </ul>

        {{ form.submit }}
    </fieldset>
</form>


{% endblock %}

grocery_app/templates/new_item.html
{% extends 'base.html' %}
{% block content %}

<h1>New Item</h1>

<form method="POST" action="{{ url_for('main.new_item') }}">

    {{ form.csrf_token }}

    <fieldset>
        <legend>Please enter your information:</legend>

        {{ form.name.label }}
        {{ form.name }}
        <ul>
            {% for error in form.name.errors %}
            <li class="error">{{ error }}</li>
            {% endfor %}
        </ul>
        
        {{ form.price.label }}
        {{ form.price}}
        <ul>
            {% for error in form.price.errors %}
            <li class="error">{{ error }}</li>
            {% endfor %}
        </ul>

        {{ form.category.label }}
        {{ form.category }}
        <ul>
            {% for error in form.category.errors %}
            <li class="error">{{ error }}</li>
            {% endfor %}
        </ul>
        
        {{ form.photo_url.label }}
        {{ form.photo_url}}
        <ul>
            {% for error in form.photo_url.errors %}
            <li class="error">{{ error }}</li>
            {% endfor %}
        </ul>

        {{ form.store.label }}
        {{ form.store}}
        <ul>
            {% for error in form.store.errors %}
            <li class="error">{{ error }}</li>
            {% endfor %}
        </ul>
            
        {{ form.submit }}

    </fieldset>
</form>


{% endblock %}

grocery_app/templates/new_store.html
{% extends 'base.html' %}
{% block content %}

<h1>New Store</h1>

<form method="POST" action="{{ url_for('main.new_store') }}">

    {{ form.csrf_token }}


    <fieldset>
        <legend>Please enter your information:</legend>

            {{ form.title.label }}
            {{ form.title }}
            <ul>
                {% for error in form.title.errors %}
                <li class="error">{{ error }}</li>
                {% endfor %}
            </ul>
            
            {{ form.address.label }}
            {{ form.address}}
            <ul>
                {% for error in form.address.errors %}
                <li class="error">{{ error }}</li>
                {% endfor %}
            </ul>
                
            {{ form.submit }}

        <!-- <input type="submit" value="Submit"> -->
    </fieldset>
</form>


{% endblock %}

grocery_app/templates/shopping_list.html
{% extends 'base.html' %}
{% block content %}

<h1>My Shopping List</h1>

<ul>
{% for item in user_shopping_items %}
    <li>
        <h3>Item - {{ item.name }}</h3>

        <p><img src="{{ item.photo_url }}" width="250px" height="250px"></p>

        <p><strong>Price:</strong> {{ item.price }}</p>

        <p><strong>Category:</strong> {{ item.category }}</p>

        <p><strong>Store:</strong> {{ item.store.title }}</p>

        <p><em>Created by:</em> {{ item.created_by }}</p>
    </li>
{% endfor %}
</ul>

{% endblock %}

grocery_app/templates/signup.html
{% extends 'base.html' %}
{% block content %}

<h1>Sign Up</h1>

<form action="/signup" method="POST">
    {{ form.csrf_token }}
    <fieldset>
        {{ form.username.label }}
        {{ form.username }}
        <ul>
        {% for error in form.username.errors %}
            <li class="error">{{ error }}</li>
        {% endfor %}
        </ul>

        {{ form.password.label }}
        {{ form.password }}
        <ul>
        {% for error in form.password.errors %}
            <li class="error">{{ error }}</li>
        {% endfor %}
        </ul>

        {{ form.submit }}
    </fieldset>
</form>

{% endblock %}

grocery_app/templates/store_detail.html
{% extends 'base.html' %}
{% block content %}

<h1>Store - {{ store.title }}</h1>

<strong>Address:</strong> {{ store.address }}

<p><em>Created by:</em> {{ store.created_by }}</p>

<h2>Items</h2>

<div class="items">
    {% for item in store.items %}
    <div class="item-details">
        <a href="/item/{{ item.id }}"><img src="{{ item.photo_url }}" alt="{{ item.name }}" width="200px">
        <p><strong>{{ item.name }}</strong></p></a>
        <p><strong>Price: ${{ item.price }}</strong></p>
    </div>
    {% endfor %}
</div>


<h2>Edit Store</h2>

<form method="POST" action="{{ url_for('main.store_detail', store_id=store.id) }}">

    {{ form.csrf_token }}

    <fieldset>
        <legend>Please enter your information:</legend>

            {{ form.title.label }}
            {{ form.title }}
            <ul>
                {% for error in form.title.errors %}
                <li class="error">{{ error }}</li>
                {% endfor %}
            </ul>
            
            {{ form.address.label }}
            {{ form.address}}
            <ul>
                {% for error in form.address.errors %}
                <li class="error">{{ error }}</li>
                {% endfor %}
            </ul>
                
            {{ form.submit }}
    </fieldset>
</form>

{% endblock %}